// Code generated by running "go generate" in github.com/Andyfoo/golang/x/text. DO NOT EDIT.

package main

import (
	"github.com/Andyfoo/golang/x/text/language"
	"github.com/Andyfoo/golang/x/text/message"
	"github.com/Andyfoo/golang/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{}

// Total table size 0 bytes (0KiB); checksum: 811C9DC5
